import 'dart:async';
import 'dart:convert';
import 'dart:math' as math;
import 'dart:typed_data';
import 'package:flutter/material.dart';
import '../../../core/helpers/download_helper.dart';
import '../../../core/helpers/file_drop_helper.dart';
import '../../../core/helpers/file_picker_helper.dart';
import '../../../core/helpers/picked_file.dart';
import '../../../core/theme/app_colors.dart';
import '../../../widgets/app_card.dart';
import '../../../widgets/page_header.dart';
import '../domain/dxf_document.dart';
import '../domain/dxf_parser.dart';
import '../domain/nc_generator.dart';

class NcGeneratorScreen extends StatefulWidget { const NcGeneratorScreen({super.key}); @override State<NcGeneratorScreen> createState()=>_State(); }
class _State extends State<NcGeneratorScreen> {
  final Map<String,TextEditingController> c={
    'program':TextEditingController(text:'O0001'),'thickness':TextEditingController(text:'10'),'tool':TextEditingController(text:'1'),'toolName':TextEditingController(text:'JD-8.00'),'diameter':TextEditingController(text:'8'),'spindle':TextEditingController(text:'10000'),'feed':TextEditingController(text:'1200'),'plunge':TextEditingController(text:'300'),'safe':TextEditingController(text:'20'),'start':TextEditingController(text:'0'),'final':TextEditingController(text:'-10'),'pass':TextEditingController(text:'3'),'internal':TextEditingController(text:'0'),'external':TextEditingController(text:'0'),'scale':TextEditingController(text:'1'),'x':TextEditingController(text:'0'),'y':TextEditingController(text:'0')};
  late final Object drop; DxfDocument? document; String? fileName,error; NcProgram? program; CuttingDirection direction=CuttingDirection.ccw; bool controllerComp=false; int motion=0; double speed=1; Timer? timer;
  @override void initState(){super.initState();drop=registerFileDrop(_load);}
  @override void dispose(){timer?.cancel();unregisterFileDrop(drop);for(final x in c.values)x.dispose();super.dispose();}
  double d(String k)=>double.parse(c[k]!.text.replaceAll(',','.')); int i(String k)=>int.parse(c[k]!.text);
  Future<void> _pick()async{final f=await pickFiles(extensions:const['dxf']);if(f.isNotEmpty)_load(f.first);}
  void _load(PickedFile f){try{final doc=DxfParser.parseBytes(f.bytes);setState((){document=doc;fileName=f.fileName;error=null;program=null;motion=0;});_generate();}catch(e){setState(()=>error=e.toString().replaceFirst('FormatException: ',''));}}
  void _generate(){if(document==null)return;try{final p=NcParameters(drawingName:fileName!,programNumber:c['program']!.text.toUpperCase(),thickness:d('thickness'),toolNumber:i('tool'),toolName:c['toolName']!.text,toolDiameter:d('diameter'),spindleSpeed:i('spindle'),cuttingFeed:i('feed'),plungeFeed:i('plunge'),safeZ:d('safe'),startZ:d('start'),finalDepth:d('final'),depthPerPass:d('pass'),direction:direction,internalOffset:d('internal'),externalOffset:d('external'),coordinateScale:d('scale'),xOrigin:d('x'),yOrigin:d('y'),controllerCompensation:controllerComp);setState((){program=NcGenerator.generateProgram(document!,p);error=null;motion=0;});}catch(e){setState((){program=null;error=e.toString().replaceFirst('Invalid argument(s): ', '');});}}
  Future<void> _download()=>downloadBytes(bytes:Uint8List.fromList(utf8.encode(program!.text)),fileName:'${fileName!.replaceFirst(RegExp(r'\.dxf$',caseSensitive:false),'')}.nc',mimeType:'text/plain;charset=utf-8');
  void _play(){if(program==null||program!.motions.isEmpty)return;timer?.cancel();timer=Timer.periodic(Duration(milliseconds:(350/speed).round()),(t){if(motion>=program!.motions.length-1){t.cancel();}else setState(()=>motion++);});setState((){});}
  void _pause(){timer?.cancel();setState((){});} void _restart(){timer?.cancel();setState(()=>motion=0);}
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:AppColors.offWhite,body:LayoutBuilder(builder:(context,size){final narrow=size.maxWidth<1050;return SingleChildScrollView(padding:EdgeInsets.all(narrow?16:28),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[PageHeader(title:'DXF → SKG1625 NC Programmer',subtitle:'Analyze, compensate, program and simulate any DXF locally in your browser.',actions:[OutlinedButton.icon(onPressed:_pick,icon:const Icon(Icons.upload_file),label:const Text('Upload DXF')),FilledButton.icon(onPressed:program==null?null:_download,icon:const Icon(Icons.download),label:const Text('Download .nc'))]),const SizedBox(height:18),if(narrow)...[_settings(),const SizedBox(height:16),_workspace()]else Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:390,child:_settings()),const SizedBox(width:18),Expanded(child:_workspace())]) ]));}));
  Widget _settings()=>AppCard(title:'Program & machining setup',child:Column(children:[InkWell(onTap:_pick,child:Container(width:double.infinity,padding:const EdgeInsets.all(18),decoration:BoxDecoration(border:Border.all(color:AppColors.darkBlue),borderRadius:BorderRadius.circular(10)),child:Column(children:[const Icon(Icons.file_upload_outlined,size:32),Text(fileName??'Drop or choose a DXF',style:const TextStyle(fontWeight:FontWeight.bold)),Text(document==null?'LINE · ARC · CIRCLE · POLYLINE':'${document!.entities.length} entities loaded')]))),const SizedBox(height:14),_row('program','Program','thickness','Glass thickness',s2:'mm'),_row('tool','Tool number','toolName','Tool name',numeric2:false),_row('diameter','Tool diameter','spindle','Spindle',s1:'mm',s2:'rpm'),_row('feed','XY cutting feed','plunge','Z plunge feed',s1:'mm/min',s2:'mm/min'),_row('safe','Safe Z','start','Start Z',s1:'mm',s2:'mm'),_row('final','Final depth','pass','Depth / pass',s1:'mm',s2:'mm'),_row('internal','Internal offset','external','External offset',s1:'mm',s2:'mm'),_row('scale','Coordinate scale','x','X origin'),_field('y','Y origin'),const SizedBox(height:8),Row(children:[const Text('Direction'),const Spacer(),ChoiceChip(label:const Text('CW'),selected:direction==CuttingDirection.cw,onSelected:(_)=>setState(()=>direction=CuttingDirection.cw)),const SizedBox(width:6),ChoiceChip(label:const Text('CCW'),selected:direction==CuttingDirection.ccw,onSelected:(_)=>setState(()=>direction=CuttingDirection.ccw))]),SwitchListTile(contentPadding:EdgeInsets.zero,title:const Text('Use controller G41/G42'),subtitle:const Text('Off: geometric tool-radius offset'),value:controllerComp,onChanged:(v)=>setState(()=>controllerComp=v)),FilledButton.icon(onPressed:document==null?null:_generate,icon:const Icon(Icons.precision_manufacturing),label:const Text('Generate complete NC')),if(error!=null)Padding(padding:const EdgeInsets.only(top:10),child:Text(error!,style:const TextStyle(color:AppColors.error)))]));
  Widget _row(String a,String la,String b,String lb,{String? s1,String? s2,bool numeric2=true})=>Padding(padding:const EdgeInsets.only(bottom:10),child:Row(children:[Expanded(child:_field(a,la,s:s1)),const SizedBox(width:10),Expanded(child:_field(b,lb,s:s2,numeric:numeric2))]));
  Widget _field(String k,String label,{String? s,bool numeric=true})=>TextField(controller:c[k],keyboardType:numeric?const TextInputType.numberWithOptions(decimal:true,signed:true):null,decoration:InputDecoration(labelText:label,suffixText:s));
  Widget _workspace(){final a=program?.analysis;return Column(children:[AppCard(title:'Drawing analysis & toolpaths',child:Column(children:[if(a!=null)Wrap(spacing:20,runSpacing:8,children:[_metric('Width','${a.width.toStringAsFixed(2)} mm'),_metric('Height','${a.height.toStringAsFixed(2)} mm'),_metric('Contours','${a.contours.length}'),_metric('Closed','${a.contours.where((x)=>x.closed).length}')]),if(a?.warnings.isNotEmpty??false)...a!.warnings.map((w)=>ListTile(dense:true,leading:const Icon(Icons.warning_amber,color:Colors.orange),title:Text(w))),SizedBox(height:350,width:double.infinity,child:document==null?const Center(child:Text('Upload a DXF to inspect all geometry.')):CustomPaint(painter:_ToolpathPainter(document!,a,program?.motions,motion)))])),const SizedBox(height:16),_simulation(),const SizedBox(height:16),AppCard(title:'Generated NC program',child:Container(height:370,width:double.infinity,padding:const EdgeInsets.all(14),color:const Color(0xff101827),child:SingleChildScrollView(child:SelectableText(program?.text??'Generate a program to preview NC output.',style:const TextStyle(fontFamily:'monospace',color:Color(0xffe5e7eb),height:1.4)))))]);}
  Widget _metric(String a,String b)=>Chip(label:Text('$a  $b'));
  Widget _simulation(){final m=program==null||program!.motions.isEmpty?null:program!.motions[motion.clamp(0,program!.motions.length-1)];return AppCard(title:'Machining simulation',child:Column(children:[Row(children:[IconButton(onPressed:_play,icon:const Icon(Icons.play_arrow)),IconButton(onPressed:_pause,icon:const Icon(Icons.pause)),IconButton(onPressed:_restart,icon:const Icon(Icons.replay)),const Text('Speed'),Expanded(child:Slider(value:speed,min:.25,max:4,divisions:15,label:'${speed.toStringAsFixed(2)}×',onChanged:(v)=>setState(()=>speed=v))]),if(m!=null)...[LinearProgressIndicator(value:(motion+1)/program!.motions.length),const SizedBox(height:8),Wrap(spacing:18,children:[Text('X ${m.end.x.toStringAsFixed(3)}'),Text('Y ${m.end.y.toStringAsFixed(3)}'),Text('Z ${m.end.z.toStringAsFixed(3)}'),Text('NC line ${m.line}'),Text(m.type.name.toUpperCase(),style:const TextStyle(fontWeight:FontWeight.bold))]),const SizedBox(height:8),Container(width:double.infinity,padding:const EdgeInsets.all(8),color:const Color(0xff101827),child:Text(program!.text.split('\n')[m.line-1],style:const TextStyle(color:Colors.amber,fontFamily:'monospace',fontWeight:FontWeight.bold))) ])) );}
}
class _ToolpathPainter extends CustomPainter{const _ToolpathPainter(this.doc,this.analysis,this.motions,this.active);final DxfDocument doc;final DrawingAnalysis? analysis;final List<NcMotion>? motions;final int active;@override void paint(Canvas canvas,Size size){final pts=doc.points.toList();if(pts.isEmpty)return;final minX=pts.map((p)=>p.x).reduce(math.min),maxX=pts.map((p)=>p.x).reduce(math.max),minY=pts.map((p)=>p.y).reduce(math.min),maxY=pts.map((p)=>p.y).reduce(math.max),scale=math.min((size.width-30)/math.max(1,maxX-minX),(size.height-30)/math.max(1,maxY-minY));Offset q(double x,double y)=>Offset(15+(x-minX)*scale,size.height-15-(y-minY)*scale);for(var ci=0;ci<(analysis?.contours.length??0);ci++){final paint=Paint()..style=PaintingStyle.stroke..strokeWidth=(motions!=null&&motions!.isNotEmpty&&motions![active.clamp(0,motions!.length-1)].contour==ci)?3:1.5..color=analysis!.contours[ci].kind==ContourKind.externalPerimeter?Colors.blue:Colors.teal;for(final s in analysis!.contours[ci].segments){if(s is LineSegment)canvas.drawLine(q(s.start.x,s.start.y),q(s.end.x,s.end.y),paint);if(s is ArcSegment){var a1=math.atan2(-(s.start.y-s.center.y),s.start.x-s.center.x),a2=math.atan2(-(s.end.y-s.center.y),s.end.x-s.center.x),sweep=a2-a1;if(s.fullCircle)sweep=s.clockwise?2*math.pi:-2*math.pi;else if(s.clockwise&&sweep<0)sweep+=2*math.pi;else if(!s.clockwise&&sweep>0)sweep-=2*math.pi;canvas.drawArc(Rect.fromCircle(center:q(s.center.x,s.center.y),radius:s.radius*scale),a1,sweep,false,paint);}}}if(motions!=null&&motions!.isNotEmpty){final p=motions![active.clamp(0,motions!.length-1)].end;canvas.drawCircle(q(p.x,p.y),6,Paint()..color=Colors.red);}}@override bool shouldRepaint(covariant _ToolpathPainter old)=>true;}
