enum HistoryAction {
  created,
  updated,
  statusChanged,
  departmentAdvanced,
  departmentCompleted,
  inspectionStarted,
  inspectionCompleted,
  assigned,
  unassigned,
  onHold,
  resumed,
  cancelled,
  completed,
  noteAdded,
  workStarted,
  workPaused,
  workResumed,
  progressSaved,
  photoUploaded,
  reworkCreated,
  qualityApproved,
  labelPrinted,
  deliveryUpdated,
  customerConfirmed,
  transferred,
  fileUploaded,
  materialsUpdated;

  String get label => switch (this) {
        HistoryAction.created => 'Order Created',
        HistoryAction.updated => 'Order Updated',
        HistoryAction.statusChanged => 'Status Changed',
        HistoryAction.departmentAdvanced => 'Department Advanced',
        HistoryAction.departmentCompleted => 'Department Completed',
        HistoryAction.inspectionStarted => 'Inspection Started',
        HistoryAction.inspectionCompleted => 'Inspection Completed',
        HistoryAction.assigned => 'Operator Assigned',
        HistoryAction.unassigned => 'Operator Unassigned',
        HistoryAction.onHold => 'Placed On Hold',
        HistoryAction.resumed => 'Production Resumed',
        HistoryAction.cancelled => 'Order Cancelled',
        HistoryAction.completed => 'Order Completed',
        HistoryAction.noteAdded => 'Note Added',
        HistoryAction.workStarted => 'Work Started',
        HistoryAction.workPaused => 'Work Paused',
        HistoryAction.workResumed => 'Work Resumed',
        HistoryAction.progressSaved => 'Progress Saved',
        HistoryAction.photoUploaded => 'Photo Uploaded',
        HistoryAction.reworkCreated => 'Rework Order Created',
        HistoryAction.qualityApproved => 'Quality Approved',
        HistoryAction.labelPrinted => 'Label Printed',
        HistoryAction.deliveryUpdated => 'Delivery Updated',
        HistoryAction.customerConfirmed => 'Customer Confirmed',
        HistoryAction.transferred => 'Transferred to Next Department',
        HistoryAction.fileUploaded => 'File Uploaded',
        HistoryAction.materialsUpdated => 'Materials Updated',
      };

  static HistoryAction fromString(String value) {
    return HistoryAction.values.firstWhere(
      (action) => action.name == value,
      orElse: () => HistoryAction.updated,
    );
  }
}
