// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqCAatF7QEiS3SwtJULyNRVrjxAvF6phI',
    appId: '1:340919504848:web:47bb2fdca74566795ff3d5',
    messagingSenderId: '340919504848',
    projectId: 'glass-factory-suite',
    authDomain: 'glass-factory-suite.firebaseapp.com',
    storageBucket: 'glass-factory-suite.firebasestorage.app',
    measurementId: 'G-CWZCQVQ02W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC32r-CcQ513F7Egx8Noar6YI_fVwMVBlk',
    appId: '1:340919504848:android:10c88b74f65121915ff3d5',
    messagingSenderId: '340919504848',
    projectId: 'glass-factory-suite',
    storageBucket: 'glass-factory-suite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCReqDZaDJswUjW2lekSIV5ma4eOYCtcA8',
    appId: '1:340919504848:ios:b8ce3e0677a946d45ff3d5',
    messagingSenderId: '340919504848',
    projectId: 'glass-factory-suite',
    storageBucket: 'glass-factory-suite.firebasestorage.app',
    iosBundleId: 'com.example.glassPactoryProduction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCReqDZaDJswUjW2lekSIV5ma4eOYCtcA8',
    appId: '1:340919504848:ios:b8ce3e0677a946d45ff3d5',
    messagingSenderId: '340919504848',
    projectId: 'glass-factory-suite',
    storageBucket: 'glass-factory-suite.firebasestorage.app',
    iosBundleId: 'com.example.glassPactoryProduction',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqCAatF7QEiS3SwtJULyNRVrjxAvF6phI',
    appId: '1:340919504848:web:1ca9500f5bd320cc5ff3d5',
    messagingSenderId: '340919504848',
    projectId: 'glass-factory-suite',
    authDomain: 'glass-factory-suite.firebaseapp.com',
    storageBucket: 'glass-factory-suite.firebasestorage.app',
    measurementId: 'G-VB7L82F9GX',
  );
}
